spring.application.name=meal-manager

spring.datasource.url=jdbc:postgresql://localhost:5000/meal_manager
spring.datasource.username=postgres
spring.datasource.password=ILearnSQL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
